export type Lang = 'zh' | 'en'
export type ThemeMode = 'system' | 'light' | 'dark'
export type Mode = 'book' | 'oracle' | 'slip'

export const copy = {
  zh: {
    mark: '答案之書',
    modes: [
      { id: 'book' as const, label: '翻書' },
      { id: 'oracle' as const, label: '問答' },
      { id: 'slip' as const, label: '抽籤' },
    ],
    coverKicker: 'THE BOOK OF ANSWERS',
    coverSub: '一頁，即是回音',
    open: '默問，然後翻開',
    questionPh: '問題可以寫下，也可以只放在心裡',
    prev: '上一頁',
    next: '下一頁',
    seek: '再求一頁',
    close: '合上',
    ask: '請問',
    again: '再問一次',
    draw: '抽一張',
    redraw: '再抽一張',
    pageLabel: (n: number) => `第 ${n} 頁`,
    ofCount: (n: number) => `共 ${n} 則`,
    history: '最近',
    about: '關於',
    soundOn: '關閉紙聲',
    soundOff: '打開紙聲',
    themeSystem: '跟隨系統',
    themeLight: '淺色',
    themeDark: '深色',
    toZh: '中文',
    toEn: '英文',
    heard: '你帶來的句子',
    quiet: [
      '心裡那一句，不必被看見。',
      '問完，就把手放開。',
      '不要向旁邊的人解釋。',
      '如果你慌了，先摸紙的邊緣。',
      '答案不追人。人自己停。',
      '同一題，不要連問三次。',
    ],
    oracleKicker: '把問題交給空白',
    oracleIdle: '在心裡問完，或寫在下面。',
    slipHint: '點一下這疊紙。',
    slipIdle: '還沒抽出來。',
    aboutTitle: '關於這本書',
    aboutBody: [
      '這不是占卜，是一次把決定交還給你的停頓。',
      '先在心裡問完，再翻開。問題可以寫下來，也可以不寫。',
      '翻書能逐頁讀，也能隨機求一頁。問答是一句話落地。抽籤是更快的一次。',
      '同一個問題，不要連問三次。若答案刺耳，先合上，明天再來。',
    ],
    aboutNote: (n: number) =>
      `共 ${n} 則，中英對照，皆為原創，與任何已出版的《答案之書》無關。`,
    keys: '鍵盤：左右方向鍵翻頁，空白鍵再求一頁，1、2、3 切換讀法。',
    footer: (n: number) => `${n} 則原創 · 與已出版的答案之書無關`,
    running: '答案之書',
    runningQ: '問',
  },
  en: {
    mark: 'Answers',
    modes: [
      { id: 'book' as const, label: 'Volume' },
      { id: 'oracle' as const, label: 'Ask' },
      { id: 'slip' as const, label: 'Draw' },
    ],
    coverKicker: 'THE BOOK OF ANSWERS',
    coverSub: 'One page. Then nothing more.',
    open: 'Ask in silence, then open',
    questionPh: 'Write the question, or leave it unspoken',
    prev: 'Previous',
    next: 'Next',
    seek: 'Another page',
    close: 'Close',
    ask: 'Ask',
    again: 'Ask again',
    draw: 'Draw one',
    redraw: 'Draw again',
    pageLabel: (n: number) => `Page ${n}`,
    ofCount: (n: number) => `${n} in all`,
    history: 'Recent',
    about: 'About',
    soundOn: 'Turn paper sound off',
    soundOff: 'Turn paper sound on',
    themeSystem: 'System',
    themeLight: 'Light',
    themeDark: 'Dark',
    toZh: 'Chinese',
    toEn: 'English',
    heard: 'The sentence you brought',
    quiet: [
      'The sentence in your chest need not be seen.',
      'Once you have asked, unclench your hand.',
      'Do not explain it to the person beside you.',
      'If you panic, touch the edge of the paper.',
      'The answer does not chase. You stop.',
      'Do not ask the same question three times.',
    ],
    oracleKicker: 'Give the question to the blank',
    oracleIdle: 'Ask it in the mind, or write it below.',
    slipHint: 'Touch the stack.',
    slipIdle: 'Nothing drawn yet.',
    aboutTitle: 'About this book',
    aboutBody: [
      'This is not fortune-telling. It is a pause that hands the decision back to you.',
      'Ask in silence, then open. You may write the question, or not.',
      'The volume can be read page by page, or opened at random. Ask lets one sentence land. Draw is the quicker rite.',
      'Do not ask the same question three times. If the answer stings, close the book and return tomorrow.',
    ],
    aboutNote: (n: number) =>
      `${n} original replies, in Chinese and English. Not the published Book of Answers, and not affiliated with it.`,
    keys: 'Keys: arrow keys turn the page, space asks again, 1 2 3 switch modes.',
    footer: (n: number) => `${n} original replies · not a published book of answers`,
    running: 'THE BOOK OF ANSWERS',
    runningQ: 'Question',
  },
}

export type Copy = (typeof copy)['zh']
